NEURALG_MIN_SYM_MATRIX_SIZE = 3
NEURALG_MAX_SYM_MATRIX_SIZE = 20

NEURALG_MIN_REAL_MATRIX_SIZE = 3
NEURALG_MAX_REAL_MATRIX_SIZE = 10

NEURALG_MIN_COMPLEX_MATRIX_SIZE = 3
NEURALG_MAX_COMPLEX_MATRIX_SIZE = 5

NEURALG_SUPPORTED_OPERATIONS = ["eig"]
